# BASE IMAGE - NOT FOR PRODUCTION #####################
# Minimal and appless FROST+PG set up. 
# Note that this compose includes:
# - NO python application                             
# - NO FROST authentication
# - NO volume persistence                             
# See README for more.
# #####################################################
services:
  web:
    image: fraunhoferiosb/frost-server:2.6
    environment:
      - serviceRootUrl=http://localhost:8080/FROST-Server
      - plugins_multiDatastream.enable=false
      - http_cors_enable=true
      - http_cors_allowed_origins=*
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
      - persistence_autoUpdateDatabase=true
    ports:
      - 8080:8080
    volumes:
      - ./init-frost.sh:/init-frost.sh
    secrets:
      - postgres_credentials
    depends_on:
      database:
        condition: service_healthy
    entrypoint: ["/init-frost.sh"]

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
    secrets:
      - mqtt_credentials
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/init-mosquitto.sh:/mosquitto/init-mosquitto.sh:ro
    entrypoint: ["/mosquitto/init-mosquitto.sh"]

  database:
    image: postgis/postgis:16-3.4-alpine
    environment:
      - POSTGRES_DB=sensorthings
    secrets:
      - postgres_credentials
    healthcheck:
      test: |
          PGUSER=$$(awk -F'"' '/"postgres_user"/ {print $$4}' /run/secrets/postgres_credentials) 
            pg_isready -d sensorthings -U "$$PGUSER"
      interval: 2s
      timeout: 2s
      retries: 10
    volumes:
      - ./init-db.sh:/init-db.sh
    entrypoint: ["./init-db.sh"]

secrets:
  postgres_credentials:
    file: ./secrets/credentials/postgres_credentials.json
  mqtt_credentials:
    file: ./secrets/credentials/mqtt_credentials.json
