# SENSOR TYPE: Netatmo NWS03
# INSTRUCTIONS
# 1 - Input the data near the *fill tag AND remove the tag
# 2 - ONE (1) Sensor per config file,
# 3 - Filename, sensor key / sensor name attribute should be device MAC address,
# 4 - iot_links shall use entity NAMES to refer to other entities,
sensors:
  netatmo.nws03:
    name: 70:ee:50:7f:a4:76
    description: Netatmo NWS03
    metadata: none
    encodingType: text
    properties:
      connectivity: Wi-Fi 802.11 b/g/n (2.4 GHz)
      recording_frequency: 5 minutes
      accuracy:
        temperature: ± 0.3°C
        humidity: 3%
        pressure: ± 1mbar
      measurement_range:
        temperature: 0°C to 50°C
        humidity: 0% to 100%
        pressure: 260mbar to 1160mbar
        CO2: 0ppm to 5000ppm
        noise: 35db to 120db
    iot_links:
      datastreams: &datastreams
        - temperature_indoor
        - humidity
        - co2
        - gauge_pressure
        - noise
        - absolute_pressure

things:
  TU Delft VR Lab:
    name: TU Delft VR Lab
    description: The VR Lab at the Bouwkunde (Architecture Faculty) at the TU Delft
    properties: null
    iot_links:
      datastreams: *datastreams
      locations:
        - TU Delft BK.BG.West.290

locations:
  TU Delft BK.BG.West.290:
    name: TU Delft BK.BG.West.290
    description: TU Delft VR Lab on the First Floor of the West Wing of the BK Building in Delft, The Netherlands.
    properties: null
    encodingType: application/geo+json
    location: # GeoJSON geometry field
      type: Point
      coordinates:  [52.00537, 4.37043]
    iot_links:
      things:
        - TU Delft VR Lab

datastreams:
  temperature_indoor:
    name: temperature_indoor
    description: This datastream is measuring the internal room temperature.
    observationType: instant
    unitOfMeasurement: &temperature
      name: degree Celsius
      symbol: °C
      definition: https://unitsofmeasure.org/ucum#para-30
    observedArea: &observedArea # GeoJSON geometry field
      type: Polygon
      coordinates: null
    phenomenon_time: null
    result_time: null
    properties: null
    iot_links:
      observedProperties:
        - indoor_temperature
      sensors:
        - 70:ee:50:7f:a4:76
      things:
        - TU Delft VR Lab

  humidity:
    name: humidity
    description:  Datastream for observations of humidity levels in TU Delft VR Lab.
    observationType: instant
    unitOfMeasurement:
      name: percent
      symbol: "%"
      definition: https://unitsofmeasure.org/ucum#para-29
    observedArea: *observedArea
    phenomenon_time: null
    result_time: null
    properties: null
    iot_links:
      observedProperties:
        - internal_humidity
      sensors:
        - 70:ee:50:7f:a4:76
      things:
        - TU Delft VR Lab

  co2:
    name: co2
    description:  Datastream for observations of CO2 levels in TU Delft VR Lab.
    observationType: instant
    unitOfMeasurement:
      name: parts per million
      symbol: ppm
      definition: https://unitsofmeasure.org/ucum#para-29
    observedArea: *observedArea
    phenomenon_time: null
    result_time: null
    properties: null
    iot_links:
      observedProperties:
        - co2_levels
      sensors:
        - 70:ee:50:7f:a4:76
      things:
        - TU Delft VR Lab

  gauge_pressure:
    name: gauge_pressure
    description:  Datastream for observations of pressure levels in TU Delft VR Lab.
    observationType: instant
    unitOfMeasurement: &millibar
      name: millibar
      symbol: mbar
      definition: https://unitsofmeasure.org/ucum#datyp2apdxatblxmp
    observedArea: *observedArea
    phenomenon_time: null
    result_time: null
    properties: null
    iot_links:
      observedProperties:
        - gauge_pressure
      sensors:
        - 70:ee:50:7f:a4:76
      things:
        - TU Delft VR Lab

  absolute_pressure:
    name: absolute_pressure
    description: Datastream for observations of absolute pressure levels in TU Delft VR Lab.
    observationType: instant
    unitOfMeasurement: *millibar
    observedArea: *observedArea
    phenomenon_time: null
    result_time: null
    properties: null
    iot_links:
      observedProperties:
        - absolute_pressure
      sensors:
        - 70:ee:50:7f:a4:76
      things:
        - TU Delft VR Lab

  noise:
    name: noise
    description:  Datastream for observations of noise levels in TU Delft VR Lab.
    observationType: instant
    unitOfMeasurement:
      name: decibel
      symbol: db
      definition: https://unitsofmeasure.org/ucum#para-46
    observedArea: *observedArea
    phenomenon_time: null
    result_time: null
    properties: null
    iot_links:
      observedProperties:
        - internal_noise_levels
      sensors:
        - 70:ee:50:7f:a4:76
      things:
        - TU Delft VR Lab

observedProperties:
  indoor_temperature:
    name: indoor_temperature
    definition: https://dbpedia.org/page/Temperature
    description: The temperature where the indoor module is placed.
    properties: null

  absolute_pressure:
    name: absolute_pressure
    definition: https://en.wikipedia.org/wiki/Pressure_measurement#Absolute
    description: The absolute pressure where the indoor module is placed.
    properties: null

  gauge_pressure:
    name: gauge_pressure
    definition: https://en.wikipedia.org/wiki/Pressure_measurement#Absolute
    description: The gauge pressure where the indoor module is placed.
    properties: null

  internal_noise_levels:
    name: internal_noise_levels
    definition: https://en.wikipedia.org/wiki/Ambient_noise_level
    description: The internal ambient noise level where the sensor is placed.
    properties: null

  co2_levels:
    name: co2_levels
    definition: https://en.wikipedia.org/wiki/Indoor_air_quality#Carbon_dioxide
    description: The C02 levels wherever the indoor module is placed.
    properties: null

  internal_humidity:
    name: internal_humidity
    definition: https://en.wikipedia.org/wiki/Humidity
    description: The internal humidity levels wherever the indoor sensor is placed.
    properties: null

